### ISSUE TITLE
Error when generating a report in Word format

### ISSUE THREAD

**Issue by eduzimrs** [AsBuiltReport/AsBuiltReport.Veeam.VB365#4]
### Bug description

Hi,

Getting the following error when using format = word.
Running the PS with admin privileges.

```
New-AsBuiltReport : The variable '$Images' cannot be retrieved because it has not been set.
At line:1 char:1
+ New-AsBuiltReport -Report Veeam.VB365 -Target VBM365.plattanolabs.com ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport
```

![image](https://user-images.githubusercontent.com/7524875/229549570-971f2fe7-7e7a-4510-959b-a87e0220293b.png)

### Command-line input

New-AsBuiltReport -Report Veeam.VB365 -Target VBM365.plattanolabs.com.br -Format Word -OutputFolderPath 'C:\temp' -EnableHealthCheck

### Steps to reproduce

ran the command

### Expected behaviour

Word  format report

### Operating System

Windows Server 2016 Datacenter

### PowerShell Version

```
PS C:\Users\administrator.PLATTANOLABS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.5582
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.5582
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### PowerShell Modules

```
Name                      Version
----                      -------
AsBuiltReport.Core        1.3.0
AsBuiltReport.Veeam.VB365 0.1.1
PScribo                   0.10.0
```

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://www.asbuiltreport.com/about/contributing/#reporting-issues-and-bugs).
- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this bug report.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.Veeam.VB365/issues) before submitting this bug report.

**Comment by rebelinux** [comment]
Could you do a test by disabling the generation of the cover page image?

Step 1: Generate a ReportConfig

New-AsBuiltReportConfig -Report Veeam.VB365 -FolderPath <User specified folder> -Filename <Optional>

Step 2: Set ShowCoverPageImage to false

![image](https://user-images.githubusercontent.com/1002783/229601120-71d18a01-d13c-4491-8ee6-32b893815268.png)

Step 3: Run the report using the new configuration file.

New-AsBuiltReport -Report Veeam.VB365 -Target veeam-vbr365.pharmax.local -Username 'Domain\veeam_admin' -Password 'P@ssw0rd' -Format Html,Word -OutputFolderPath 'C:\Users\Jon\Documents' **-ReportConfigFilePath 'C:\Users\Jon\AsBuiltReport\AsBuiltReport.Veeam.VB365.json'** -Verbose

Documentation: 

https://github.com/AsBuiltReport/AsBuiltReport.Veeam.VB365#pencil2-configuration

**Comment by eduzimrs** [comment]
Hi,

It worked without the Cover page set to true.
Thanks.
